### ISSUE TITLE
Unable to deploy on Netlify due to dependencies and Decap CMS login issues

### ISSUE THREAD

**Issue by leonardobetti** [ositaka/nextjs-blog-tailwind-starter#1]
Hi folks

First of all, thank you and congrats on the project!. The design looks sleek, and I’m considering using it for a directory website that I’m building as a side project. However, I’m encountering some issues when trying to deploy using Netlify. I’ve enabled Identity, but unfortunately, there are several dependency issues, and the server fails to deploy. It seems there is a problem with the import of the package @mdx-js/react. Additionally, I’ve tried using Decap CMS locally. The login page loads, but there is no option to register or any clear instructions on how to log in.

If someone could kindly help me resolve these issues, I’d really appreciate it. I’m just trying to publish on Netlify, enable Decap CMS, and tweak a few settings.

Thank you in advance.

```
2:09:22 PM:  ✓ Compiled successfully
2:09:22 PM:    Linting and checking validity of types ...
2:09:27 PM: Failed to compile.
2:09:27 PM: 
2:09:27 PM: ./components/InspirationPost.tsx:9:36
2:09:27 PM: Type error: Cannot find module 'mdx/types' or its corresponding type declarations.
2:09:27 PM:    7 | import PostFooter from './PostFooter'
2:09:27 PM:    8 | import Video from './/Video'
2:09:27 PM: >  9 | import type { MDXComponents } from 'mdx/types'
2:09:27 PM:      |                                    ^
2:09:27 PM:   10 |
2:09:27 PM:   11 | export default function InspirationPost({
2:09:27 PM:   12 |   inspiration,
2:09:27 PM:  ELIFECYCLE  Command failed with exit code 1. (https://ntl.fyi/exit-code-1)
2:09:27 PM: ​
2:09:27 PM: "build.command" failed                                        
2:09:27 PM: ────────────────────────────────────────────────────────────────
2:09:27 PM: ​
2:09:27 PM:   Error message
2:09:27 PM:   Command failed with exit code 1: pnpm run build (https://ntl.fyi/exit-code-1)
2:09:27 PM: ​
2:09:27 PM:   Error location
2:09:27 PM:   In Build command from Netlify app:
2:09:27 PM:   pnpm run build
2:09:27 PM: ​
2:09:27 PM:   Resolved config
2:09:27 PM:   build:
2:09:27 PM:     command: pnpm run build
2:09:27 PM:     commandOrigin: ui
2:09:27 PM:     publish: /opt/build/repo/.next
2:09:27 PM:     publishOrigin: ui
2:09:27 PM:   plugins:
2:09:27 PM:     - inputs: {}
2:09:27 PM:       origin: ui
2:09:27 PM:       package: '@netlify/plugin-nextjs'
2:09:28 PM: Failed during stage 'building site': Build script returned non-zero exit code: 2 (https://ntl.fyi/exit-code-2)
2:09:28 PM: Build failed due to a user error: Build script returned non-zero exit code: 2
2:09:28 PM: Failing build: Failed to build site
2:09:28 PM: Finished processing build request in 1m7.981s
```

**Comment by leonardobetti** [comment]
<img width="725" alt="Screenshot 2024-10-16 at 14 28 00" src="https://github.com/user-attachments/assets/7a356509-3f2d-4a23-8ebe-15300269e8a5">

CMS screenshot, how to login?

**Comment by ositaka** [comment]
> <img alt="Screenshot 2024-10-16 at 14 28 00" width="725" src="https://private-user-images.githubusercontent.com/32095528/377072765-7a356509-3f2d-4a23-8ebe-15300269e8a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwODY4NDMsIm5iZiI6MTcyOTA4NjU0MywicGF0aCI6Ii8zMjA5NTUyOC8zNzcwNzI3NjUtN2EzNTY1MDktM2YyZC00YTIzLThlYmUtMTUzMDAyNjllOGE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDEzNDkwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmN2UxYzEwY2IzYTU4ZGU0M2JhYmQyOTgzNGY2Y2RjODRkODk0MDFkODMwNGNiMTA0YzUyMTZlOGM3MWM5MWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Jap0-Rd60PEq_QMXAzoYD6LgdOCAF0hBjFWCnokqrC4">
> CMS screenshot, how to login?

You can see on the Read Me how to use the CMS locally. Please have a look on the `Note`: https://github.com/ositaka/nextjs-blog-tailwind-starter?tab=readme-ov-file#%EF%B8%8F-decap-cms

Regarding the deploy I will have a better look later. Do you have any public repo that I could have a look at?

**Comment by leonardobetti** [comment]
Confirming from my end, already changed `local_backend: true` still same issue, unable to login on my local machine. I was able to deploy just using the _Deploy to Netlify_ button so website up and running [here](https://tlx-design.netlify.app/), however unable to login using Decap CMS same screen above when I reach .. /admin/index.html 
Git Gateway already enable, I also invited myself and included as admin inside Netfly Identity tab. Thanks in advance.

```
backend:
  name: git-gateway
  branch: main
  local_backend: true
```

**Comment by leonardobetti** [comment]
so sorry, just saw an youtube video about Decap CMS and I fixed it the file. I suggest add pnpm install decap-cms-app --save on the read.me also the site-wide registration below. Still having many depencies issues but the website is running now, thanks.

```
<script>
  if (window.netlifyIdentity) {
    window.netlifyIdentity.on("init", (user) => {
      if (!user) {
        window.netlifyIdentity.on("login", () => {
          document.location.href = "/admin/";
        });
      }
    });
  }
</script>
```

**Comment by ositaka** [comment]
> so sorry, just saw an youtube video about Decap CMS and I fixed it the file. I suggest add pnpm install decap-cms-app --save on the read.me also the site-wide registration below. Still having many depencies issues but the website is running now, thanks.
> 
> ```
> <script>
>   if (window.netlifyIdentity) {
>     window.netlifyIdentity.on("init", (user) => {
>       if (!user) {
>         window.netlifyIdentity.on("login", () => {
>           document.location.href = "/admin/";
>         });
>       }
>     });
>   }
> </script>
> ```

I see the problem... As this starter is a clone of the https://design-code.tips/ I've forgot to add that netlify identity block on this starter. I will fix it today!

Thank you for taking the time to open this issue! If you find any other "critical issue", please let me know and I'll fix it.
